Prashanth code test
Superformula/flutter_test-2023 pull request #5
Opened 2022-06-21 16:06 UTC by prashanthvontela

Implemented the challenge using MVVM pattern and used Providers for state management.
Used all stateless widgets to all screen layouts.

Know Isse:
Handled favotites locally, not used any stored preferences. Applied logic and work in single app instance only. 
Once we kill the app, the fourites list will reset.
Not added test cases. Will add and update you.

2022-06-30 17:17 UTC, spencer-sf reviewed
Hey Prashanth, thanks for taking the time to submit the challenge. Sorry for the delay in getting it reviewed! When reviewing these submissions I like to review as if they were being committed to a client repo, to convey the code standard we strive for here at Superformula so that means there's a lot of nit-picking comments and cleanup tasks. Don't worry about addressing those or pushing any updates to your submission, just look over the feedback and be prepared to answer the questions posed in our follow up review interview! Thanks again for the great submission, and someone will be reaching out soon to schedule your next interview!

2022-06-30 17:17 UTC, spencer-sf commented on lib/app_routes/app_routes.dart
> +  static setUpRoutes(BuildContext context) {
**question**: Are there any future scalability issues by making this static?

2022-06-30 17:17 UTC, spencer-sf commented on lib/features/restauran_tour/model/restauran_service.dart
> +  }) : yelpRepo = yelpRepo ?? YelpRepository();
**question**: Can you explain why you use the default value here in the constructor instead of just passing in a valid instance?

2022-06-30 17:17 UTC, spencer-sf commented on lib/features/restauran_tour/model/restauran_service.dart
> +  Future<Object> getAllRestaurans({int offSet = 0}) async {
**fix-it**: Returning an `Object` type is really bad practice, you may have to make a parent class to return both a `Success` and a `Failure` object depending on outcome.

2022-06-30 17:17 UTC, spencer-sf commented on lib/features/restauran_tour/model/restauran_service.dart
> +        errorResponse: "INVALID RESPONSE",
**question**: Is there a dynamic, more helpful message to pass in here?

2022-06-30 17:17 UTC, spencer-sf commented on lib/features/restauran_tour/view/all_restaurants_screen.dart
> +  Widget _viewMoreButton(BuildContext context, RestaurantsViewModel viewModel) {
**question**: Any performance drawbacks returning a widget from a function?

2022-06-30 17:17 UTC, spencer-sf commented on lib/features/restauran_tour/view/restaurant_detail_screen.dart
> +            _detailContent(context, viewModel.selectedRestaurant),
same as above regarding widgets returned from functions

2022-06-30 17:17 UTC, spencer-sf commented on lib/features/restauran_tour/view/restaurant_detail_screen.dart
> +                viewModel.rating.toString(),
**nit-pick**: No need to pass entire viewModel object to reference a single field

2022-06-30 17:17 UTC, spencer-sf commented on lib/features/restauran_tour/view/restaurant_detail_screen.dart
> +          OpenStatus(viewModel.isOpen)
**nit-pick**: No need to pass entire viewModel object to reference a single field

2022-06-30 17:17 UTC, spencer-sf commented on lib/features/restauran_tour/view/restaurant_detail_screen.dart
> +            viewModel.location?.displayAddress ?? "",
**nit-pick**: No need to pass entire viewModel object to reference a single field

2022-06-30 17:17 UTC, spencer-sf commented on lib/features/restauran_tour/view/restaurant_detail_screen.dart
> +    return (viewModel.reviews != null && viewModel.reviews!.isNotEmpty)
**nit-pick**: No need to pass entire viewModel object to reference a single field

2022-06-30 17:17 UTC, spencer-sf commented on lib/features/restauran_tour/view/restaurant_detail_screen.dart
> +                    generateReviewComments(context, viewModel.reviews ?? []),
**question**: We know `viewModel.reviews != null && viewModel.reviews!.isNotEmpty` why have a default?

2022-06-30 17:17 UTC, spencer-sf commented on lib/features/restauran_tour/view/restaurant_row_item.dart
> +        padding: const EdgeInsets.symmetric(vertical: 4, horizontal: 4),
**chore**: `EdgeInsets.all(4)`

2022-06-30 17:17 UTC, spencer-sf commented on lib/features/restauran_tour/view_model/restaurants_view_model.dart
> +    this.service = service ?? RestauranService();
Same question as `RestauranService` construction above

2022-06-30 17:17 UTC, spencer-sf commented on lib/features/restauran_tour/view_model/restaurants_view_model.dart
> +    var res = await service?.getAllRestaurans(offSet: offSet);
**fix-it**: The service should never be null here. If you're intending to `getAllRestaurants` there should never be a question to the consumer about whether or not it's making a call. Especially since there is no error handling if `service` is null

2022-06-30 17:17 UTC, spencer-sf commented on lib/features/restauran_tour/view_model/restaurants_view_model.dart
> +    getAllRestaurants(offSet: _offSet, isRefresh: false);
```suggestion
    getAllRestaurants(offSet: ++_offSet, isRefresh: false);
```

2022-06-30 17:17 UTC, spencer-sf commented on lib/features/restauran_tour/view_model/restaurants_view_model.dart
> +    return favoriteRestaurants;
```suggestion
    return _restaurantsList.where((e) => _favoriteList(contains(e.id)).toList();
```

2022-06-30 17:17 UTC, spencer-sf commented on lib/main.dart
> +        ChangeNotifierProvider(create: (_) => RestaurantsViewModel()),
**question**: Is there a way to break `RestaurantsViewModel` into smaller chunks so it isn't managing the state of the entire application?

2022-06-30 17:17 UTC, spencer-sf commented on lib/repositories/api_status.dart
> +}
**question**: Do these fields have enough in common to make a parent class that would satisfy a typed return in the function mentioned earlier?

2022-06-30 17:17 UTC, spencer-sf commented on lib/widgets/load_more_button.dart
> +      padding: const EdgeInsets.symmetric(horizontal: 4, vertical: 4),
```suggestion
      padding: const EdgeInsets.all(4),
```

2022-06-30 17:17 UTC, spencer-sf commented on test/features/restauran_tour_test/mock_restauran_service.dart
> +  Future<Object> getAllRestaurans({int offSet = 0}) async {
**question**: Is there a better way to mock a service that allows for testing different function results? (Error, success, bad data etc..)

2022-06-30 17:17 UTC, spencer-sf commented on test/features/restauran_tour_test/restaurants_view_model_test.dart
> +    await tester.pump(const Duration(seconds: 2));
```suggestion
    await tester.pumpAndSettle();
```

2022-06-30 17:17 UTC, spencer-sf commented on test/features/restauran_tour_test/restauran_tour_test.dart
> +    /// Load the app with material app configuration
**question**: Why doc comments?

2022-06-30 17:17 UTC, spencer-sf commented on test/features/restauran_tour_test/restauran_tour_test.dart
> +    await tester.pumpAndSettle();
**suggestion**: Tests should be as small as possible, testing only one component in each test. Consider breaking these into separate tests

2022-06-30 17:17 UTC, spencer-sf commented on test/features/restauran_tour_test/restauran_tour_test.dart
> +    expect(find.widgetWithText(Tab, "All Resturants"), findsOneWidget);
**nit-pick**: Changing the text on the tab in the UI will cause this test to break, move to a constant pattern to avoid test brittleness

2022-06-30 17:17 UTC, spencer-sf commented on test/features/restauran_tour_test/restauran_tour_test.dart
> +  // testWidgets('open restauran detail screen', (WidgetTester tester) async {
**nit-pick**: Tests are equally as important as features, don't merge code with failing/commented out tests

2022-06-30 17:17 UTC, spencer-sf commented on test/features/restauran_tour_test/restauran_tour_test.dart
> +  //   await _createWidget(tester);
**bug-fix**: When inflating the material widget to test, you have to have a route handler to test navigation so mocking one out will fix this test

2022-06-30 17:17 UTC, spencer-sf commented on test/features/restauran_tour_test/restaurants_view_model_test.dart
> +  testWidgets('Check all restautant list got loaded',
**question**: Since all of these functions provide only business logic, can they be tested with a unit test instead of a widget test?

2022-07-04 22:53 UTC, enzo-sf requested changes

2022-07-04 22:53 UTC, enzo-sf commented on lib/app_routes/app_routes.dart
> +          const ResturantDetailScreen(),
suggestion: In both cases, context is not used. So it could be removed to improve readability.

```suggestion
      initialRoute: (_) => const RestauranTour(),
      restaurantDetailRoute: (_) => const ResturantDetailScreen(),
```

2022-07-04 22:53 UTC, enzo-sf commented on lib/features/restauran_tour/model/restauran_service.dart
> +      );
suggestion: prefer `final` over `var` if the value is not going to be updated.

2022-07-04 22:53 UTC, enzo-sf commented on lib/repositories/endpoints.dart
> +const String restauranUrl = "/v3/graphql";
typo: restaurant

2022-07-04 22:53 UTC, enzo-sf commented on lib/repositories/endpoints.dart
> +const String restauranUrl = "/v3/graphql";
typo: Also in `restaurant_service.dart`

2022-07-04 22:53 UTC, enzo-sf commented on lib/features/restauran_tour/model/restauran_service.dart
> +      if (200 == response.statusCode) {
I know it's the same but it's a personal preference
```suggestion
      if (HttpStatus.ok == response.statusCode) {
```

2022-07-04 22:53 UTC, enzo-sf commented on lib/features/restauran_tour/model/restauran_service.dart
> +  String _getQuery(int offset) {
suggestion: improve naming (like `_getRestaurantsQuery`)

2022-07-04 22:53 UTC, enzo-sf commented on lib/features/restauran_tour/model/restauran_service.dart
> +''';
thought: One of the key arguments in favor of graphql is that we don't need to fetch information that will not be required for that specific view. If you take a look into the restaurant item view you don't need `reviewers` 
and `location`.

<img width="479" alt="image" src="https://user-images.githubusercontent.com/95098927/177221856-b1564521-02cd-4db7-aed6-6fa8f0524ae8.png">

2022-07-04 22:53 UTC, enzo-sf commented on lib/features/restauran_tour/model/restauran_service.dart
> +''';
Also some of the requirements it's the loading state for the detail screen. So probably my suggestion it's to split this into 2 different queries one for the restaurant list and the other one for detail.

<img width="408" alt="image" src="https://user-images.githubusercontent.com/95098927/177222113-624ef5a8-3fe5-4f29-a09c-aa8cffaa8128.png">

2022-07-04 22:53 UTC, enzo-sf commented on lib/features/restauran_tour/view/restaurant_detail_screen.dart
> +      ),
suggestion: Instead of using 2 nested widgets take advantage of the more accurated

```suggestion
    body: ListView(
        children: [
          _imageDisplay(context, viewModel.selectedRestaurant.heroImage),
          _detailContent(context, viewModel.selectedRestaurant),
        ],
      ),
```

2022-07-04 22:53 UTC, enzo-sf commented on lib/features/restauran_tour/view_model/restaurants_view_model.dart
> +  RestauranService? service;
suggestion: Instead of declaring this as nullable (this would never happen) make it `late` to initialize it later

```suggestion
  late RestauranService service;
```

2022-07-04 22:53 UTC, enzo-sf commented on lib/features/restauran_tour/view_model/restaurants_view_model.dart
> +  }
Instead of handling this on memory, you should make here the query to fetch the detail as I mentioned before

2022-07-04 22:53 UTC, enzo-sf commented on lib/widgets/rating.dart
> +  final double? rating;
thought: I think that this does not need to be nullable.

2022-07-04 22:55 UTC, enzo-sf commented
improvement-bug: Set a fixed height for the image on the detail screen.

<img width="476" alt="image" src="https://user-images.githubusercontent.com/95098927/177223418-0c2d4441-eb5f-4ac1-807f-0a3b0094091c.png">

2022-07-04 23:01 UTC, enzo-sf commented
Hi @prashanthvontela, very nice challenge! As @spencer-sf mentioned we take a review as it would be a real client project, so every suggestion it's made with love ✌️.

Also, I want to second Spencer in some suggestions so you can take care of it in the future.
- Use Widget (stless) instead of functions that return widgets
- Don't return `Object`
- Avoid passing whole objects just for single fields
- Keep your test as small as possible

2024-02-05 20:24 UTC, closed without merging